# Generated by Django 4.1.4 on 2022-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_konstitsiya_modda_bolimfk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
