# Generated by Django 4.1.3 on 2022-12-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_tibbiy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hordiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
